name: build_push_gcr_job
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
    secrets:
      gcloud_service_key:
        required: true
  
jobs:
  build_push:
    name: Build and Push to GCR
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.gcloud_service_key }} # can be base64 encoded or plain text
        registry: us-east1-docker.pkg.dev/baccoapp-358901/gcr-baccoapp
        project_id: baccoapp-358901
        image_name: ${{ env.project }}-${{ github.ref_name }}
        image_tag: latest,${{ github.run_number }}
        dockerfile: ./BaccoApp.UserManagement.Api/Dockerfile
